fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
        language_version: python3.11
      - id: poetry-export
        name: poetry-export-prod
        args: [ "-f", "requirements.txt", "--only", "main", "-o", "requirements/prod.txt" ]
        verbose: true
      - id: poetry-export
        name: poetry-export-test
        args: [ "-f", "requirements.txt", "--with", "test", "-o", "requirements/test.txt" ]
        verbose: true
      - id: poetry-export
        name: poetry-export-dev
        args: [ "-f", "requirements.txt", "--with", "test,dev", "-o", "requirements/dev.txt" ]
        verbose: true

  - repo: https://github.com/klen/pylama
    rev: 8.4.1
    hooks:
      - id: pylama
        args: ["passbot", "tests"]
        additional_dependencies:
          - toml

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - sqlalchemy[mypy]==2.0.3
          - pydantic==1.10.4
          - types-python-slugify==8.0.0.0
        files: ^(passbot|tests)
        exclude: ^passbot/crawlers/(middlewares.py|settings.py)$
        language_version: python3.11
