services:

  passbot:
    image: passbot/crawlers:latest
    container_name: passbot_crawlers
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
