services:

  passbot:
    image: passbot/crawlers:dev
    container_name: passbot_crawlers
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.dev
    volumes:
      - .:/code

  postgres:
    image: postgres:latest
    container_name: passbot_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
