services:

  passbot:
    image: passbot/crawlers:dev
    container_name: passbot_crawlers
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
      - .env.dev
    volumes:
      - .:/code
