services:

  passbot:
    image: passbot/crawlers:latest
    container_name: passbot_crawlers
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: prod.Dockerfile
    env_file:
      - .env.prod

  postgres:
    image: postgres:latest
    container_name: passbot_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
